# Generated by Django 4.2.3 on 2023-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='about',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
