# Generated by Django 4.2.3 on 2023-07-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_about_members_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='about',
            field=models.TextField(blank=True, help_text='Input some text about member...', null=True),
        ),
    ]
